# Generated by Django 5.0.7 on 2024-10-24 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adminapp", "0005_alter_feedback_name_alter_feedback_phonenumber_and_more"),
        ("facultyapp", "0002_alter_addcourse_course_alter_addcourse_section"),
    ]

    operations = [
        migrations.CreateModel(
            name="Marks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course",
                    models.CharField(
                        choices=[
                            ("AOOP", "Advanced Object-Oriented Programming"),
                            ("PFSD", "Python Full Stack Development with Django"),
                        ],
                        max_length=50,
                    ),
                ),
                ("marks", models.IntegerField()),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="adminapp.studentlist",
                    ),
                ),
            ],
        ),
    ]
