# Generated by Django 5.0.7 on 2024-10-15 12:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adminapp", "0003_feedback"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedback",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="feedback",
            name="text_field",
        ),
        migrations.RemoveField(
            model_name="feedback",
            name="username",
        ),
        migrations.AddField(
            model_name="feedback",
            name="name",
            field=models.CharField(default="Anonymous", max_length=100),
        ),
        migrations.AddField(
            model_name="feedback",
            name="phonenumber",
            field=models.CharField(default="0123456789", max_length=10),
        ),
        migrations.AddField(
            model_name="feedback",
            name="textfield",
            field=models.TextField(default="Feedback"),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="email",
            field=models.EmailField(max_length=100),
        ),
    ]
