# Generated by Django 5.0.7 on 2024-10-17 08:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adminapp", "0004_remove_feedback_phone_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="phonenumber",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="textfield",
            field=models.TextField(max_length=150),
        ),
    ]
